import React, { useState, useEffect } from "react";
import axios from "axios";
import { useParams } from "react-router-dom";

function CatDetail() {
  const {catId} = useParams()
  const [cat, setCat] = useState(null);

  useEffect(() => {
  

      axios
        //id autogenerated by Mongoose
        .get(`/api/cats/${catId}`)
        .then((res) => {
          setCat(res.data);
        })
        .catch((error) => {
          console.error("Error fetching cat details:", error);
        });
  
  }, [catId]);

  if (!cat) {
    return <div>Loading...</div>;
  }
  // Function to calculate calorie intake based on weight
  function calculateCalorieIntake(weight) {
    return Math.round(weight * 20);
  }

  return (
    <div>
      <h2>{cat.name}</h2>
      {/* <img src={cat.image} alt={cat.name} /> */}
      <p>Breed: {cat.breed}</p>
      <p>Age: {cat.age} years</p>
      <p>Weight: {cat.weight} lbs</p>
      <p>Calorie Intake: {calculateCalorieIntake(cat.weight)} kcal/day</p>

      <a href={`/cats/${cat._id}/edit`}>Need to make changes?</a>
    </div>
  );
}

export default CatDetail;


